SET SERVEROUTPUT ON;
SET VERIFY OFF;

BEGIN
	DBMS_OUTPUT.PUT_LINE('PLEASE INSERT PROPER INFORMATION!');
END;
/

ACCEPT A CHAR PROMPT 'Book Name = '
ACCEPT B CHAR PROMPT 'Genre of Book = '
ACCEPT C CHAR PROMPT 'Author Name = '
ACCEPT D CHAR PROMPT 'Entry Date(YYYY/MM/DD) = '

DECLARE
	NUM NUMBER;
	B_ID BOOKS.BOOKS_ID%TYPE;
	B_NAME BOOKS.BOOKS_NAME%TYPE;
	B_GENRE BOOKS.BOOK_GENRE%TYPE;
	B_AUTHOR BOOKS.AUTHOR%TYPE;
	B_DATE BOOKS.B_ENTRY_DATE%TYPE;

BEGIN

	B_NAME := '&A';
	B_GENRE := '&B';
	B_AUTHOR := '&C';
	B_DATE := TO_DATE('&D', 'YYYY/MM/DD');
	
	SELECT COUNT(BOOKS_ID) INTO NUM FROM BOOK_COLLECTION;
	B_ID := NUM+1;
	
	IF B_DATE >= TO_DATE('2010/01/01', 'YYYY/MM/DD')THEN
		INSERT INTO BOOKS VALUES(B_ID, UPPER(B_NAME), UPPER(B_GENRE), UPPER(B_AUTHOR), B_DATE);
	ELSE 
		INSERT INTO BOOKS@SITE1 VALUES(B_ID, UPPER(B_NAME), UPPER(B_GENRE), UPPER(B_AUTHOR), B_DATE);
	END IF;
	
	EXCEPTION
		WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('FORMAT WRONG! PLEASE USE INSTRUCTED FORMAT.');
END;
/
COMMIT;

@"D:\4.1\DDS-LAB\Z_LABPROJECT\Personal Collection Tracker\site1\show_collection.sql"