SET SERVEROUTPUT ON;
SET VERIFY OFF;
		
BEGIN
	DBMS_OUTPUT.PUT_LINE(chr(10)||chr(10)||'Please Enter your Choice:');
	DBMS_OUTPUT.PUT_LINE('1. Search for any Stamp');
	DBMS_OUTPUT.PUT_LINE('2. Search for any Book');
	DBMS_OUTPUT.PUT_LINE(chr(10) || '-------Please Keep the unnecessary input fields blank--------');
END;
/

DECLARE
	CHOICES NUMBER := &YOUR_CHOICE;
	CHOICE_OUT_OF_BOUND EXCEPTION;
	
    STMP_CODE STAMPS.STAMP_CODE%TYPE := UPPER('&Your_Stamp_Code');
	STMP_COUNTRY STAMPS.COUNTRY%TYPE := UPPER('&Country');
	STMP_YEAR STAMPS.STAMP_YEAR%TYPE := '&YEAR';
	STMP_PRICE STAMPS.PRICE%TYPE := '&Stamp_Price'; 
	STMP_DATE STAMPS.S_ENTRY_DATE%TYPE := TO_DATE('&Stamp_Entry_date','YYYY/MM/DD' );
	
	BNAME BOOKS.BOOKS_NAME%TYPE := UPPER('&Your_Book_Name');
	BGENRE BOOKS.BOOK_GENRE%TYPE := UPPER('&Genre_of_Book');
	BAUTHOR BOOKS.AUTHOR%TYPE := UPPER('&Author_Name');
	BDATE BOOKS.B_ENTRY_DATE%TYPE := TO_DATE('&Book_Entry_date','YYYY/MM/DD' );
	
	
BEGIN
	IF CHOICES = 1 THEN
		--DBMS_OUTPUT.PUT_LINE(CHOICES);
		MY_PACK_COL.SEARCH_STAMP_COL(STMP_CODE, STMP_COUNTRY, STMP_YEAR,  STMP_PRICE, STMP_DATE);
	ELSIF CHOICES = 2 THEN 
		--DBMS_OUTPUT.PUT_LINE(CHOICES);
		MY_PACK_COL.SEARCH_BOOK_COL(BNAME, BGENRE, BAUTHOR, BDATE);
		
	END IF;
	
	IF CHOICES > 2 OR CHOICES < 0 THEN
		RAISE CHOICE_OUT_OF_BOUND;
	END IF;
	
	EXCEPTION
		WHEN CHOICE_OUT_OF_BOUND THEN 
			DBMS_OUTPUT.PUT_LINE(chr(10)||'WRONG CHOICE OPTION SELECTED!');
	
END;
/

@"D:\4.1\DDS-LAB\Z_LABPROJECT\Personal Collection Tracker\site1\updateCollection.sql"