SET SERVEROUTPUT ON;
SET VERIFY OFF;
		
BEGIN
	DBMS_OUTPUT.PUT_LINE(chr(10)||chr(10)||'Please Enter your Choice:');
	DBMS_OUTPUT.PUT_LINE('1. Show Stamp Collection');
	DBMS_OUTPUT.PUT_LINE('2. Show Book Collection');
END;
/

DECLARE
	CHOICES INT := &YOUR_CHOICE;
	CHOICE_OUT_OF_BOUND EXCEPTION;

BEGIN
	IF CHOICES = 1 THEN
		--DBMS_OUTPUT.PUT_LINE(CHOICES);
		MY_PACK_COL.SHOW_STAMP_COL;
	ELSIF CHOICES = 2 THEN 
		MY_PACK_COL.SHOW_BOOK_COL;
	END IF;
	
	IF CHOICES > 2 OR CHOICES < 0 THEN
		RAISE CHOICE_OUT_OF_BOUND;
	END IF;
	
	EXCEPTION
		WHEN CHOICE_OUT_OF_BOUND THEN 
			DBMS_OUTPUT.PUT_LINE(chr(10)||'WRONG CHOICE OPTION SELECTED!');
			
END;
/

