set linesize 300;
set pagesize 600;

CREATE OR REPLACE VIEW STAMP_COLLECTION AS
SELECT * FROM STAMPS
UNION 
SELECT * FROM STAMPS@SITE1;

CREATE OR REPLACE VIEW BOOK_COLLECTION AS
SELECT * FROM BOOKS
UNION 
SELECT * FROM BOOKS@SITE1;

SELECT * FROM STAMP_COLLECTION;
SELECT * FROM BOOK_COLLECTION;

CREATE OR REPLACE VIEW SEARCH_COLLECTION1 AS
SELECT STAMP_CODE, COUNTRY, STAMP_YEAR, PRICE, S_ENTRY_DATE  FROM STAMP_COLLECTION;

CREATE OR REPLACE VIEW SEARCH_COLLECTION2 AS
SELECT BOOKS_NAME, BOOK_GENRE, AUTHOR, B_ENTRY_DATE FROM BOOK_COLLECTION;

