SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PACKAGE DEL_UP_COL AS
	PROCEDURE ALL_COL(CH IN NUMBER, CID IN BOOKS.BOOKS_ID%TYPE);
	FUNCTION ALL_COL_UD(CHC IN NUMBER, CO_ID IN STAMPS.STAMP_ID%TYPE, CO_DATE IN STAMPS.S_ENTRY_DATE%TYPE)
	RETURN NUMBER;
END DEL_UP_COL;
/



CREATE OR REPLACE PACKAGE BODY DEL_UP_COL AS

-------------------------------DELTE COLLECTION FOR STAMPS AND BOOKS----------------------------------

	PROCEDURE ALL_COL(CH IN NUMBER, CID IN BOOKS.BOOKS_ID%TYPE)
	IS
	BEGIN
		IF CH = 1 THEN
			DELETE FROM STAMPS@SITE1 WHERE STAMP_ID = CID;
		ELSIF CH = 2 THEN
			DELETE FROM STAMPS WHERE STAMP_ID = CID;
		ELSIF CH = 3 THEN
			DELETE FROM BOOKS@SITE1 WHERE BOOKS_ID = CID;
		ELSIF CH = 4 THEN
			DELETE FROM BOOKS WHERE BOOKS_ID = CID;
		END IF;
		COMMIT;
	END ALL_COL;
	
	-------------------------------UPDATE COLLECTION FOR STAMPS AND BOOKS----------------------------------
	
	FUNCTION ALL_COL_UD(CHC IN NUMBER, CO_ID IN STAMPS.STAMP_ID%TYPE, CO_DATE IN STAMPS.S_ENTRY_DATE%TYPE)
	RETURN NUMBER
	IS
	
	BEGIN
		IF CHC = 1 THEN
			UPDATE STAMPS@SITE1 SET S_ENTRY_DATE = CO_DATE where STAMP_ID = CO_ID;
		ELSIF CHC = 2 THEN
			UPDATE STAMPS SET S_ENTRY_DATE = CO_DATE where STAMP_ID = CO_ID;
		ELSIF CHC = 3 THEN
			UPDATE BOOKS@SITE1 SET B_ENTRY_DATE = CO_DATE where BOOKS_ID = CO_ID;
		ELSIF CHC = 4 THEN
			UPDATE BOOKS SET B_ENTRY_DATE = CO_DATE where BOOKS_ID = CO_ID;
		END IF;
		COMMIT;
	RETURN 1;
	END ALL_COL_UD;
	
	
	
END DEL_UP_COL;
/	
